import type { Product, User } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Cà phê Arabica Đà Lạt",
    description:
      "Cà phê Arabica nguyên chất từ cao nguyên Đà Lạt, rang xay theo phương pháp truyền thống, hương vị đậm đà, thơm ngon.",
    price: 250000,
    original_price: 300000,
    image: "/vietnamese-arabica-coffee-beans-dalat.jpg",
    images: [
      "/vietnamese-arabica-coffee-beans-dalat.jpg",
      "/coffee-plantation-dalat-highlands.jpg",
      "/roasted-coffee-beans-close-up.jpg",
    ],
    category: "coffee",
    in_stock: true,
    stock_quantity: 100,
    rating: 4.8,
    review_count: 124,
    tags: ["organic", "premium", "arabica"],
    origin: "Đà Lạt, Lâm Đồng",
    weight: "500g",
    ingredients: ["100% cà phê Arabica"],
  },
  {
    id: "2",
    name: "Trà Atisô Đà Lạt",
    description: "Trà atisô tự nhiên từ Đà Lạt, giúp thanh nhiệt, giải độc, tốt cho sức khỏe gan và hệ tiêu hóa.",
    price: 180000,
    image: "/vietnamese-artichoke-tea-dalat.jpg",
    images: [
      "/vietnamese-artichoke-tea-dalat.jpg",
      "/artichoke-flowers-field-vietnam.jpg",
      "/dried-artichoke-tea-leaves.jpg",
    ],
    category: "tea",
    in_stock: true,
    stock_quantity: 50,
    rating: 4.6,
    review_count: 89,
    tags: ["herbal", "healthy", "natural"],
    origin: "Đà Lạt, Lâm Đồng",
    weight: "200g",
    ingredients: ["100% hoa atisô khô"],
  },
  {
    id: "3",
    name: "Rượu Vang Đà Lạt",
    description: "Rượu vang đỏ cao cấp từ nho trồng tại Đà Lạt, hương vị đậm đà, phù hợp cho những dịp đặc biệt.",
    price: 450000,
    original_price: 500000,
    image: "/vietnamese-red-wine-dalat-bottle.jpg",
    images: [
      "/vietnamese-red-wine-dalat-bottle.jpg",
      "/grape-vineyard-dalat-vietnam.jpg",
      "/wine-tasting-glass-red-wine.jpg",
    ],
    category: "wine",
    in_stock: true,
    stock_quantity: 25,
    rating: 4.7,
    review_count: 56,
    tags: ["premium", "red wine", "local"],
    origin: "Đà Lạt, Lâm Đồng",
    weight: "750ml",
    ingredients: ["Nho đỏ Đà Lạt", "Men rượu tự nhiên"],
  },
  {
    id: "4",
    name: "Dâu Tây Tươi Đà Lạt",
    description: "Dâu tây tươi ngon, ngọt tự nhiên từ các trang trại Đà Lạt, giàu vitamin C và chất chống oxy hóa.",
    price: 120000,
    image: "/fresh-strawberries-dalat-vietnam.jpg",
    images: [
      "/fresh-strawberries-dalat-vietnam.jpg",
      "/strawberry-farm-dalat-greenhouse.jpg",
      "/ripe-red-strawberries-basket.jpg",
    ],
    category: "fruits",
    in_stock: true,
    stock_quantity: 30,
    rating: 4.9,
    review_count: 203,
    tags: ["fresh", "organic", "vitamin-c"],
    origin: "Đà Lạt, Lâm Đồng",
    weight: "500g",
    ingredients: ["100% dâu tây tươi"],
  },
  {
    id: "5",
    name: "Mứt Dâu Tây Đà Lạt",
    description: "Mứt dâu tây thơm ngon, làm từ dâu tây tươi Đà Lạt, không chất bảo quản, phù hợp làm quà tặng.",
    price: 85000,
    image: "/strawberry-jam-vietnamese-traditional.jpg",
    images: [
      "/strawberry-jam-vietnamese-traditional.jpg",
      "/homemade-strawberry-preserve-jar.jpg",
      "/strawberry-jam-on-bread.jpg",
    ],
    category: "preserves",
    in_stock: true,
    stock_quantity: 75,
    rating: 4.5,
    review_count: 78,
    tags: ["handmade", "no-preservatives", "gift"],
    origin: "Đà Lạt, Lâm Đồng",
    weight: "300g",
    ingredients: ["Dâu tây tươi", "Đường mía", "Nước cốt chanh"],
  },
  {
    id: "6",
    name: "Cà Phê Robusta Đặc Biệt",
    description:
      "Cà phê Robusta đặc biệt với hương vị mạnh mẽ, đậm đà, phù hợp cho những ai yêu thích vị cà phê truyền thống.",
    price: 200000,
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "coffee",
    in_stock: true,
    stock_quantity: 80,
    rating: 4.4,
    review_count: 95,
    tags: ["robusta", "strong", "traditional"],
    origin: "Đà Lạt, Lâm Đồng",
    weight: "500g",
    ingredients: ["100% cà phê Robusta"],
  },
]

export const mockUser: User = {
  id: "1",
  email: "user@example.com",
  name: "Nguyễn Văn A",
  phone: "0123456789",
  address: "123 Đường ABC, Phường XYZ",
  role: "customer",
  created_at: "2024-01-01T00:00:00Z",
}

export const mockAdmin: User = {
  id: "admin",
  email: "admin@dacsanlamdong.vn",
  name: "Admin",
  role: "admin",
  created_at: "2024-01-01T00:00:00Z",
}

export const products = mockProducts
